/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-random.h
 #	source generated by 4D Plugin Wizard
 #	Project : random
 #	author : miyako
 #	2020/04/16
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_RANDOM_H
#define PLUGIN_RANDOM_H

#include "4DPluginAPI.h"

#include "4DPlugin-JSON.h"

#include "C_BLOB.h"
#include "C_LONGINT.h"
#include "C_TEXT.h"

#pragma mark -

#if VERSIONWIN
#include <bcrypt.h>
#include <stdio.h>
#pragma comment(lib, "bcrypt")
#endif

static void generate_random_number(PA_PluginParameters params);
static void generate_random_bytes(PA_PluginParameters params);

#endif /* PLUGIN_RANDOM_H */
